quick-lint/quick-lint-js

- src/include/quick-lint-js/parse.h
- test/test-parse.cpp
Parsing a `debugger` statement follows the same behavior as parsing a `break`/`continue` statement.
#6 As far as I am concerned, quick-lint-js already knew that `debugger` was a keyword and not an identifier.
> Parse debugger statements

- src/include/quick-lint-js/error.h
- src/include/quick-lint-js/lex.h
- src/lex.cpp
- test/test-lex.cpp
Here is my attempt at #32.
I have one question (at least). When I use `u8"123___45___67"` as input, `"123___"`, `"45___"`, and `"67"` are all considered different tokens. I found this out when I was getting a test failure that I was not at `token_type::end_of_file`. Is this intentional, or do you want me to include an update to make it consider the whole thing one token?
On one hand, it seems like it should be one token. On the other hand, each group of consecutive underscores is currently reported as a separate linting error, with no special walking to make it happen.
I look forward to your feedback. I haven't written C++ since high school 20 years ago, so I appreciate you letting us contribute!
> Add errors for consecutive underscores

- src/include/quick-lint-js/options.h
- src/main.cpp
- src/options.cpp
- test/test-options.cpp
Here is the implementation i did. I created a simple lambda helper to print the different options but i used `const char *` in order to pass the arguments, don't know if that's right. I saw that you had a padded-string helper but not sure if i should use it or this is ok.
> Help option

- src/include/quick-lint-js/parse.h
- src/parse.cpp
- test/test-parse.cpp
For report missing semicolon for variable declarations, I left out the `if`, `try`, `with`, `class`, and `function` cases. I wasn't too sure if they should all be included. On second thought they probably should be included.
I was going to add more cases, for report invalid binding in let statement, but things are already getting messy. I'm not sure if you should be able to recover from the `if` case (just telling the lexer to skip). For the number and `debugger` case, I believe you should be able to just skip over and continue because it is one token.
I wasn't sure how to title the commit. I wanted to have two separate commits, "Report missing semicolon for variable declarations" and "Report debugger as invalid binding in let statement", but I couldn't figure out how to split the commit …
> Report missing semicolon for variable declarations and report debugger as invalid binding in let statement

- .gitignore
- dist/default.nix
- dist/quick-lint-js.nix
- dist/shell.nix
- docs/BUILDING.md
- docs/INSTALLING.md
This adds a new directory containing packaging tools `dist/`. For now,
this only includes nix derivations which allow building and packaging
through the nix package manager[1].
Most of the work for the nix derivation is done by the build hook for
cmake[2]. There is some funkyness going on during the install phase
so we overwrite it with our custom installPhase that only installs
the binary file. This can be extended in the future to also include
library files and manpages (if applicable).
The build results are:
```
$ tree result
result
└── bin
└── quick-lint-js
1 directory, 1 file
```
```
$ ./result/bin/quick-lint-js --help
Usage: quick-lint-js [OPTIONS]... [FILE]...
OPTIONS
--output-format=[FORMAT]            Format to print feedback where FORMAT is one of:
gnu-like (default if omitted), …
```
> Add nix build expressions and instructions

- test/test-parse.cpp
In pull request #39 I forgot to write a test for the commit "Continue parsing after invalid let binding".
> Test continue parsing after invalid let binding

- .github/workflows/build-and-test-dev-env-nix.yml
Runs the developer build instructions for nix on ubuntu as described
in `BUILDING.md`, runs the tests and runs the binary with `--help` in and outside of `nix-shell`.
This uses https://github.com/cachix/install-nix-action to install nix
Possible future improvements:
- Make test also run on maxos with nix-darwin
- Create new test which does install / execute / uninstall with `nix-env -i` as described in `INSTALLING.md`
> Add github workflow for building nix dev env

- src/main.cpp
- src/quick-lint-js/error-tape.h
Hi.
First, I do hope you are all fine and the same for your relatives.
I modified linter code to first uses EXIT_SUCCESS and EXIT_FAILURE macros instead of 0 and 1.
I do not know if this a good practice in C++ but in C this a good one (see [this post](https://stackoverflow.com/a/8868139)).
Then I added a static variable to error_exporter class.
This variable can be seed as a fuse, it is initialized as false and set to true by text_reporter::report.
Finally, it is tested in main and if is true main returns EXIT_FAILURE.
For now, I only modified text_reporter::report and not other reporters.
Please let me know if I should do it or if there is problem with the code.
Indeed, I am not very skilled in C++ so using static variable is maybe a bad approach.
Best regards.
> Returns EXIT_FAILURE if an error was reported

- .github/workflows/build-and-test-dev.yml
- docs/BUILDING.md
The building documentation now uses `cd "$OLDPWD"` over `cd -`. This change stops the redundant printing of the current working directory that `cd -` performs.
The build and test dev workflow that follows the building documentation has been updated to match this change.
> Update building documentation

- src/lex.cpp
- test/test-lex.cpp
Resolves a lingering issue in #10 
Currently in a multi-line string literal, if the line ends with CRLF, quick-lint incorrectly reports 'unclosed string literal'.
```javascript
let a = 'hello \
world.'
```
This removes the error.
Also add a test to ensure that all line ending types are allowed in a string literal if escaped with a backslash.
> Allow escaped newlines with CRLF

- src/main.cpp
- src/options.cpp
- test/test-options.cpp
When I was working on #208, I noticed another warning that is in a suboptimal location and is untested. This PR addresses that.
> Refactor files_to_lint warning into dump_errors + test

- src/error-list.cpp
- src/options.cpp
- src/quick-lint-js/error-list.h
- test/test-options.cpp
Yet another parameter that should warn when `--lsp-server` is used.
A part of https://github.com/quick-lint/quick-lint-js/pull/208 and https://github.com/quick-lint/quick-lint-js/issues/202
> warn when --exit-fail-on is used with --lsp-server

- website/install.html
This change allows users to select installation commands using only one click and it avoids selecting the leading `$`.
One downside is that users won't be able to select a portion of the installation command.
Not sure if this would be appropriate for the entire site so I put it inside of the style element for the HTML.
https://user-images.githubusercontent.com/32761424/114309850-aa7d5d00-9ab6-11eb-91fe-8faf75a4c487.mp4
https://user-images.githubusercontent.com/32761424/114309853-ac472080-9ab6-11eb-8095-d7a6ef6496dd.mp4
> Highlight installation commands with one click

- website/demo/index.html
https://user-images.githubusercontent.com/32761424/115054415-2f4cea00-9eae-11eb-9034-0e7e471d6f07.mp4
https://user-images.githubusercontent.com/32761424/115054442-34aa3480-9eae-11eb-9bc6-a98fba9f0a50.mp4
There seems to be some misalignment if you make the height too small. (potential "bug" not worth caring about)
I wasn't sure if the comment from the known bugs section referred to the fix I've implemented so I gave it it's own commit.
If it is referring to the fix, that commit should be fixup'd. If not, that commit should be dropped.
> Website: Synchronize demo's pre and textarea sizing

- docs/RELEASE.md
- docs/cli.adoc
- docs/quick-lint-js.1
- tools/generate-cli-docs
- website/cli.html
- website/index.html
- website/prepare-for-publish
Closes #224 
Notes:
* ~~The generate script requires you to be inside of the tools directory. Obviously not ideal.~~
* ~~I've added the generated documentation (cli.html, quick-lint-js.1) for ease of viewing. I don't expect this to stay.~~
* I've gone with using the default CSS (main.css).
* ~~The CSS file is inlined into the generated HTML.~~
* ~~There should probably be copyright notices in the generated documentation.~~
* There are ~~many~~ minor differences between the old man page and this new one. ~~The most notable is nested indentation. I'm not sure if this is bad for man pages.~~ quick-lint-js isn't bolded in the name section. The commas in the options are bolded.
* ~~The generated HTML currently does not contain the navigation bar footer.~~
* ~~[GitHub's adoc preview is not …
> Asciidoctor

- .github/workflows/build-and-test-dev-env-nix.yml
- .github/workflows/build-and-test-dev.yml
- .github/workflows/build-and-test-plugin-vscode.yml
- .github/workflows/build-and-test-web-demo.yml
- .github/workflows/build-and-test.yml
- .github/workflows/build-static.yml
- .github/workflows/check-copyright.yml
- .github/workflows/check-error-docs.yml
- .github/workflows/check-format.yml
- .github/workflows/debian-package.yml
- .github/workflows/simple-build.yml
- .github/workflows/test-benchmark-lsp.yml
- .github/workflows/test-emacs-plugin.yml
- .github/workflows/test-homebrew-package.yml
- .github/workflows/test-install.yml
- .github/workflows/test-nix-install.yml
- .github/workflows/test-vim-plugin.yml
As of commit cadbfbb1db664e1016a76e7cc9b2ffcc55243e6f, GitHub Actions CI
does the following on pull requests:
1. Merge the pull request source with the destination
2. If the merge succeeded:
a. Read workflow files from the merged commit
b. Run each workflow:
i. 'git clone', creating a checkout at the pull request source
Importantly, the Git commit used for the workflow files is different
from the Git commit used for the checkout. This causes problems with a
workflow file assumes a newer checkout. (For example, commit
52ed8937c74ca839f317e6a4eeb3679eae73aaaa changed a workflow file and the
checkout such that the workflow fails without an updated checkout.)
I don't know of a way to coerce GitHub to use the workflow files of the
pull request source.
Change our workflows to use GitHub's …
> CI: prevent mismatch between workflows and checkout

- src/parse.cpp
- test/test-parse-var.cpp
The following code doesn't make quick-lint-js to crash now:
let { async = 3, get = 4, set = 5 } = {};
Fix issue: #96
> Fix crash on destructuring assignment with async

- src/parse.cpp
- src/quick-lint-js/parse.h
- test/test-lint-parse.cpp
- test/test-parse-expression-statement.cpp
- test/test-parse-expression.cpp
The following code should not produce a warning (E057):
'undefined' === typeof foo ? 3 : 4;
Fix: #306
> Fix conditional operator after typeof

- tools/test-all-js-engines
test-all-js-engines uses the latest published eshost version. It seems
that version 8.0.0 is broken. test-all-js-engines used to report an
error for the following JavaScript code, but doesn't any more:
if (true)
Version 7.6.0 seems to work better. Use that working version.
> Pin to working version of eshost for test-all-js-engines

- website/public/benchmarks/index.ejs.html
- website/public/hiring/index.ejs.html
- website/public/license/index.ejs.html
Fixed validation errors in /license page where paragraph tag is not allowed to
be a children of an ordered list, and added lang attribute to html element (this
attribute was also added to /hiring and /benchmarks pages) #335. In /benchmarks page, we still get the following validation error `Error CSS: color: 70% is not a valid color 3 or 6 hexadecimals numbers`, which seems to be a validator bug. I have opened up an issue with validator, which can be tracked [here](https://github.com/validator/validator/issues/1160)
> More validation errors

- plugin/emacs/CMakeLists.txt
- plugin/emacs/README.md
- plugin/emacs/eglot-quicklintjs.el
- plugin/emacs/flycheck-quicklintjs.el
- plugin/emacs/flymake-quicklintjs.el
- plugin/emacs/lsp-quicklintjs.el
- plugin/emacs/test/quicklintjs-test.el
- src/lsp-server.cpp
- test/test-lsp-server.cpp
adds support for eglot, lsp-mode and flymake
use `--stdin` flag in flycheck
still missing update in README documentation, that's a WIP.
> improve emacs support

- docs/errors/E133.md
- docs/errors/E204.md
- src/parse.cpp
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-expression.cpp
- test/test-parse-function.cpp
*function f(x) { yield x; }
Should report error_generator_function_star_belongs_before_name
Fix: #267
> Report different error for *function f() {}

- docs/errors/E205.md
- plugin/vscode/test/other-tests.js
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-lint-parse.cpp
- test/test-parse-module.cpp
- test/test-parse-var.cpp
const x;
Should report error_missing_initializer_in_const_declaration
Fix: #252
> Report error on uninitialized declaration of const variable.

- docs/errors/E206.md
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-statement.cpp
async function f() {
await:
}
Should report error_label_named_await_not_allowed_in_async_function.
Fix: #214
> Disallow labels named 'await' in async functions

- src/parse.cpp
- test/test-parse-expression.cpp
#myvar = 42;
Should only a produce single error, error_cannot_refer_to_private_variable_without_object
> Improve error message for '#foo = bar;'

- src/parse.cpp
- test/test-parse-expression-statement.cpp
- test/test-parse-var.cpp
Resolves #215
What should be done for the broken test in test-parse-var.cpp?
Also I'm not sure what the error message should be so I just wrote random stuff.
> Disallow parameter named 'await' in async arrow function

- docs/errors/E165.md
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-class.cpp
- Reporting a `typescript_style_const_error` when a const field is used: 
```
class C {
const f = null;
}
```
quick-lint-js reported:
```
hello.js:2:3: error: unexpected token [E054]
```
quick-lint-js now reports:
```
a.js:3:3: error: const fields within classes are only allowed in TypeScript, not Javascript [E165]
```
Fixes #235
> 7$: Error with nice message when trying to use TypeScript-style const fields

- docs/errors/E207.md
- src/lex.cpp
- src/quick-lint-js/error.h
- src/quick-lint-js/lex.h
- test/test-lex.cpp
let x = "hello\u{abcdefgh}";
Should report `error_escaped_code_point_in_unicode_out_of_range`
Fix: #187
> Report invalid unicode escapes

- tools/collect-copyright
When building quick-lint-js with Address Sanitizer, generating copyright
information fails:
[57/57] Generating quick-lint-js-licenses.txt
FAILED: src/quick-lint-js-licenses.txt
cd /home/strager/quick-lint-js/build-fuzz/src && /usr/bin/python3 /home/strager/quick-lint-js/cmake/../tools/collect-copyright --linkmap /home/strager/quick-lint-js/build-fuzz/src/quick-lint-js.trace >"/home/strager/quick-lint-js/build-fuzz/src/quick-lint-js-licenses.txt"
Traceback (most recent call last):
File "/home/strager/quick-lint-js/cmake/../tools/collect-copyright", line 916, in <module>
main()
File "/home/strager/quick-lint-js/cmake/../tools/collect-copyright", line 87, in main
dump_from_linkmap(
File "/home/strager/quick-lint-js/cmake/../tools/collect-copyright", line 115, in dump_from_linkmap …
> collect-copyright: fix crash on Fedora

- docs/errors/E208.md
- src/parse.cpp
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-class.cpp
- test/test-parse-expression-statement.cpp
- test/test-parse-expression.cpp
this.#x;
Should report `error_cannot_access_private_identifier_outside_class`.
Fix: #219
> Report error on use of this.#x outside of class

- src/main.cpp
Previously there was no ": " in between "property declaration" and the name of the property, this PR fixes the formatting issue.
> Fix print formatting for property declaration for --debug-parser-visits

- completions/_quick-lint-js
- completions/quick-lint-js.bash
- completions/quick-lint-js.fish
- docs/cli.adoc
- plugin/emacs/flycheck-quicklintjs.el
- plugin/emacs/flymake-quicklintjs.el
- plugin/emacs/test/quicklintjs-test.el
- src/CMakeLists.txt
- src/emacs-lisp-error-reporter.cpp
- src/emacs-location.cpp
- src/main.cpp
- src/options.cpp
- src/quick-lint-js/emacs-lisp-error-reporter.h
- src/quick-lint-js/emacs-location.h
- src/quick-lint-js/options.h
- src/quick-lint-js/utf-8.h
- src/utf-8.cpp
- test/CMakeLists.txt
- test/test-emacs-lisp-error-reporter.cpp
- test/test-emacs-location.cpp
- test/test-options.cpp
- test/test-utf-8.cpp
notes:
I didn't ran asciidoctor to generate manpages and html because my version (debian sid) is different than previously used to generate, and it makes a diff-mess in both man and html, so left that out of the patches
emacs-location and utf8 code point counting looks awkward, i feel it could handle the case where offset is in middle of a code point by going backward, altought im unsure if i should
the exit_fail_on is ignored in main when output_format is emacs_lisp because it's the easier path i saw, im unsure if there is a better place for that, it needs to return 0 for emacs so flymake (perhaps flycheck too) can disable quick-lint-js backend if some input is crashing quick-lint-js, it avoids inifnite loops spawning quick-lint-js
> update emacs plugins error parsing

- src/parse.cpp
- test/test-parse-expression.cpp
first time touching the parser code, i hope i didn't screw up too much, i have a bad feeling about my second test case, i think errors should stop in `error_missing_operand_for_operator` and ignore `error_missing_property_name_for_dot_operator`. im spleepy atm so i couldn't find an easy path for doing that, so pardon me it should.
> fix #400: add semicol to generate an error in parse_expression_remainder

- src/parse.cpp
- test/test-parse-expression-statement.cpp
#407 
The new behavior is to end the expression for these keywords. It will not report an unexpected token error in an expression. 
Because the code continues parsing instead of crashing, there are known new issues with handling `catch`, `export`, `extends`, `finally` and `function` expressions. These issues occur when keywords are mentioned in unopened comment blocks.
For example:
```
*                  
* this function extends a string 
* /
```
> Handle unexpected keywords in expressions

- website/public/install/index.ejs.html
It seems that the warning is due to apt trying to grab packages for
unsupported architecture. Fixed by making it default to amd64. #149
> fix apt update notice

- src/quick-lint-js/parse.h
- test/test-parse-loop.cpp
for (const x of []) {}
for (const x in []) {}
Should not report `error_missing_initializer_in_const_declaration`
Fix: #380
> Don't report an error on uninitialized const in for of/in loop

- src/quick-lint-js/parse.h
- test/test-lint-parse.cpp
function f() {
await: for(;;) {
break await;
}
}
Should not report an error for `break await`.
Fix: #369
> Don't report an error on 'break await' in non-async functions and 'break yield' in non-generator functions

- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-class.cpp
- test/test-parse-expression-statement.cpp
- test/test-parse-function.cpp
let o = {
method() => {
},
};
Should report error_methods_should_not_have_arrow_operator.
Fix: #292
> Improve error when using => on object literal method

- src/parse.cpp
- src/quick-lint-js/error.h
- test/test-parse-function.cpp
let f = () {}
Should report error_missing_arrow_operator_in_arrow_function
Fix: #461
> Improve error for missing arrow operator

- plugin/emacs/README.md
- plugin/emacs/eglot-quicklintjs.el
- website/public/install/emacs/configure/index.ejs.html
At the current time, quick-lint-js's eglot setup requires that the user `M-x eglot` to start linting their code. This step can be avoided by including `(eglot-ensure)` in the `my-eglot-quicklintjs-setup` function. This is an improvement because it makes quick-lint-js integration with eglot plug and play, avoiding unnecessary steps.
> Add suggestion to make Eglot run automatically

- src/parse.cpp
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-expression.cpp
> Suggest fix for mispelled await inside async function

- src/change-detecting-filesystem-kqueue.cpp
As it seems, `NOTE_FUNLOCK` is an Apple Extension, which causes builds to fail on FreeBSD.
This fixes builds for the following targets, which I was able to test:
- FreeBSD 13.0-RELEASE-p4 GENERIC  arm64
- FreeBSD 13.0-RELEASE-p4 TRITON13 amd64
The test suites seem to be fine on both amd64 and arm64.
I got a curious little warning during the build on ARM tho:
```
[ 23%] Building CXX object src/CMakeFiles/quick-lint-js-lib.dir/file-handle.cpp.o
/home/nico/src/quick-lint-js/src/file-handle.cpp:262:2: warning: "Size returned by get_pipe_buffer_size might be inaccurate" [-W#warnings]
^
```
Don't know whether that would cause any issues on that platform.
> Fix FreeBSD build failures

- website/public/main.css
Enables dark mode on native browser controls, like buttons, scrollbars,
textareas, inputs, etc.
Before:
After:
> Website: dark mode improvements

- src/quick-lint-js/error.h
- src/quick-lint-js/parse-statement-inl.h
- test/test-parse-statement.cpp
```js
switch (true) {
console.log("banana");
case true:
case false:
default:
}
```
Should report error_statement_before_first_switch_case.
Resolve: #632
> Report error on statement before first switch case

- docs/CHANGELOG.md
Re: https://github.com/quick-lint/quick-lint-js/pull/665
`Apple calls it "Apple silicon". Let's use Apple's preferred capitalization.`:
https://developer.apple.com/documentation/apple-silicon
>  Docs: update changelog to use Apple silicon terminology.

- src/parse.cpp
- src/quick-lint-js/expression.h
- src/quick-lint-js/parse-expression-inl.h
- src/quick-lint-js/parse-statement-inl.h
- src/quick-lint-js/parse.h
- test/parse-support.cpp
- test/test-parse-expression.cpp
Refactored the parse_arrow_function_body_impl  member function by merging both expression::arrow_function_with_expression and expression::arrow_function_with_statement  classes into one, also removed the temporary expression from the function parse_arrow_function_body_impl to avoid double parsing of parameters.
I think the last item mentioned in issue #638 it's already done in this commit https://github.com/quick-lint/quick-lint-js/commit/35a362bce7e9b17252da3a0c1d11237ca9268595
> Refactor parser::parse_arrow_function_body_impl issue #638

- docs/CHANGELOG.md
- docs/errors/E0211.md
- src/quick-lint-js/error.h
- src/quick-lint-js/parse-expression-inl.h
- test/test-parse-function.cpp
This PR addresses #662 by introducing a new error type `E0211` (I'm not sure if there's a convention for these numbers, so I just went with +1)
I decided not to address the following scenario just yet:
```javascript
function() { }()
```
the reason being is that this behaves slightly differently than the arrow functions with where the surrounding parentheses are acceptable. I think this should probably be its own class of error, so the wording doesn't get confusing between the two
if you want, I can add that error type as part of this PR as well (or I can just roll it into `E0211` if you prefer that)
this was fun! thanks for coming by the stream and helping out, much appreciated
> Add new error type to address #662

- src/quick-lint-js/parse-statement-inl.h
- test/test-parse-statement.cpp
Previously, the code:
```
return
<div>hi</div>
```
wouldn't report an error. It now correctly reports E0179 when returning an html tag on a new line. I also added unit tests.
> Fixed #635 and added unit tests

- po/de.po
- src/quick-lint-js/translation-table-generated.h
- src/translation-table-generated.cpp
- test/quick-lint-js/test-translation-table-generated.h
- tools/test-translation
Updates the German po file and recompiled the translation tables.
Also, as discussed on IRC this adds the simple script that can be used to quickly test some of the translated error messages.
> Update German Translation files and add simple testing script for translation messages

- docs/BUILDING.md
I was going through BUILDING.md and found some links missing so I added them here.
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).
> fix(docs): Add links for GCC, GNU Make, and Homebrew

- src/quick-lint-js/fe/parse-expression.cpp
- test/test-parse-function.cpp
fixes #814
Looks like it failed only if the arrow function had one argument.
Before:
```javascript
// test.js
let b1 = ()  {};
let b2 = (a)  {};
let b3 = (a, a)  {};
```
```
$ ./build/quick-lint-js test.js
test.js:1:14: error: missing arrow operator for arrow function [E0176]
test.js:2:13: error: missing ',' between variable declarations [E0132]
test.js:3:18: error: missing arrow operator for arrow function [E0176]
test.js:2:11: warning: use of undeclared variable: a [E0057]
```
After:
```javascript
// test.js
let b1 = ()  {};
let b2 = (a)  {};
let b3 = (a, a)  {};
```
```
$ ./build/quick-lint-js test.js
test.js:1:14: error: missing arrow operator for arrow function [E0176]
test.js:2:15: error: missing arrow operator for arrow function [E0176]
test.js:3:18: error: missing arrow operator …
```
> Fix #814: missing arrow operator error not reported

- src/quick-lint-js/fe/parse.cpp
- test/test-parse-warning.cpp
Currently, quick-lint-js gives a warning when doing a pointless compare when using toUpperCase or toLowerCase against string literals, but it fails to do so if one of the expressions contains parenthesis e.g. 
`(s.toUpperCase()) === 'test'`
This PR intends to fix that issue and adds some tests to consider those scenarios.
> Fix: Improve check for E0286 and E0287

- src/quick-lint-js/fe/lex.cpp
- test/test-lex.cpp
fixes #528
With SIMD, parsing only comments is 59% faster, but without SIMD the fallback is now 45% slower.
On [jquery-3.6.0.js](https://code.jquery.com/jquery-3.6.0.js) the effect is very marginal. about 1% faster with SIMD and about 1% slower without.
Can I make this even faster? Maybe without losing so much performance for the fallback?
$ mkdir build ; cd build ; cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DQUICK_LINT_JS_ENABLE_BENCHMARKS=YES .. ; cd "$OLDPWD"
$ ninja -C build
$ export QLJS_LINT_BENCHMARK_SOURCE_FILE=./jquery-3.6.0.js	# or test.js
$ export QLJS_PARSE_BENCHMARK_SOURCE_FILE=./jquery-3.6.0.js	# or test.js
$ ./build/benchmark/quick-lint-js-benchmark-lint \
--benchmark_min_time=2 \
--benchmark_repetitions=10 \
--benchmark_counters_tabular=true \ …
> Fix #528: Optimize lexer::skip_line_comment_body with SIMD

- .gitignore
- docs/BUILDING.md
After I compiled and opened quick-lint-js in my editor, I realized some headers could not be found by my LSP (clangd)
I found out I needed to use `-DCMAKE_EXPORT_COMPILE_COMMANDS=1`, and now clangd can find all headers correctly
> Troubleshoot how to get clangd to correctly find all headers

- docs/errors/E0341.md
- docs/errors/E0342.md
- docs/errors/E0344.md
- docs/errors/E0345.md
- po/de.po
- po/en_US@snarky.po
- po/fr_FR.po
- po/messages.pot
- po/sv_SE.po
- src/quick-lint-js/fe/diagnostic-types.h
- src/quick-lint-js/fe/parse-expression.cpp
- src/quick-lint-js/fe/parse.cpp
- src/quick-lint-js/fe/parse.h
- src/quick-lint-js/i18n/translation-table-generated.cpp
- src/quick-lint-js/i18n/translation-table-generated.h
- test/quick-lint-js/test-translation-table-generated.h
- test/test-parse-warning.cpp
- test/test-translation-table-generated.cpp
Fixes https://github.com/quick-lint/quick-lint-js/issues/821
Now quick-lint-js gives a warning when using strict equality or inequality operators for comparing against an array literal, object literal, class literal, arrow function, or regexp literal.
> Fix 821: Warn on x === [], x === {}, etc

- website/public/install/common-debian.ejs.html
Overwrite the source list (/etc/apt/soruces.list.d/quick-lint-js.list) on multiple installs (instead of appending).
That way don't end up with spam in the terminal:
> Remove -a from tee to stop appending to source list each install

- src/quick-lint-js/fe/global-variables.cpp
- src/quick-lint-js/fe/global-variables.h
currently, this is the only global variable non standard defined by quickjs:
https://bellard.org/quickjs/quickjs.html#Global-objects
> feat(lint): ignore QuickJS scriptArgs pre defined global

- benchmark/benchmark-parse.cpp
There was one extra scope going in which was causing the depth to exceed 130. Removing just one of the curly braces causes this limit to not be reached.
> Fix crash in quick-lint-js-benchmark-parse

- docs/errors/E0451.md
- po/de.po
- po/en_US@snarky.po
- po/fr_FR.po
- po/messages.pot
- po/pt_BR.po
- po/sv_SE.po
- src/quick-lint-js/fe/diagnostic-types.h
- src/quick-lint-js/fe/parse-expression.cpp
- src/quick-lint-js/fe/parse-statement.cpp
- src/quick-lint-js/fe/parse.cpp
- src/quick-lint-js/fe/parse.h
- src/quick-lint-js/i18n/translation-table-generated.cpp
- src/quick-lint-js/i18n/translation-table-generated.h
- test/quick-lint-js/test-translation-table-generated.h
- test/test-parse-warning.cpp
- test/test-translation-table-generated.cpp
This commit adds a warning diagnostic to catch misleading comma operator usage in conditional statements of the if, while, for, and switch control blocks.
Closes #585
> Warn on comma operator in conditional statements

- docs/quick-lint-js.config.schema.json
- schema for quick-lint-js.config file
- not added '$id' for now as it needs URI for the schema file
closes #927
> feat : added quick-lint-js.schema.config file

- dist/update-release-notes.go
Fix permissions logic for warning of not having public_repo or private repo permission (for your token).
> Bug: Fix permissions warning in update-release-notes.go

- website/public/main.css
Issue: #979 we use `user-select:none` on CSS with id `error-box`
gets rid of this message "0057 - use of undeclared variable: ocupationconsole.log(`Welcome, ${occupation}!`);note: creating worker"
> BugFix: Fix copy and paste of code from demo.

- website/public/common-nav.ejs.html
#1024 
Added aria-current="page" to the correct main nav element. This was done by taking advantage of the pageLinkHTML function which already includes a check for if the current nav item is the current page.
> use aria-current to indicate current nav

- test/test-file.cpp
This fixes the following build failure when building the current master on FreeBSD:
```
test/test-file.cpp:264:20: error: no member named 'waitpid' in the global namespace
::pid_t rc = ::waitpid(pid, &status, /*options=*/0);
~~^
test/test-file.cpp:267:17: error: use of undeclared identifier 'WIFEXITED'
EXPECT_TRUE(WIFEXITED(status)) << "child should not have crashed";
^
test/test-file.cpp:268:9: error: use of undeclared identifier 'WIFEXITED'
if (WIFEXITED(status)) {
^
test/test-file.cpp:269:17: error: use of undeclared identifier 'WEXITSTATUS'
EXPECT_EQ(WEXITSTATUS(status), 0)
^
```
Fix by adding missing include of `sys/wait.h`.
I haven't looked at a different build failure (`test/test-event-loop.cpp:818:10: error: use of undeclared identifier 'NOTE_CRITICAL'`) which seems to be more …
> Partially fix build failure of test suite on FreeBSD

- website/public/contribute/build-from-source/macos/index.ejs.html
I updated the macOS instructions for building from source.
I had a few linker errors when I first tried building from source, and after a bit of debugging I realized that [Homebrew's LLVM formula installs `libc++` in `$(brew --previx)/llvm/lib/c++`](https://github.com/Homebrew/homebrew-core/commit/d3999fcadc162f4f55b3237d5636ef3e6355738a). Updating `LDFLAGS` fixed the build.
> feat(website): update macOS build instructions

- docs/CHANGELOG.md
- src/quick-lint-js/fe/parse-class.cpp
- test/test-parse-typescript-interface.cpp
This fixes an `E0054` (unexpected token) error that was reported whenever an interface property matched a keyword followed by a type.
For example, 
```ts
interface I { get: any }
```
is valid TypeScript, but quick-lint-js was reporting: 
```sh
/test.ts:1:18: error: unexpected token [E0054]
```
> fix(typescript): interface properties can be keywords followed by a type

- docs/errors/E0717.md
- po/messages.pot
- src/quick-lint-js/diag/diagnostic-metadata-generated.cpp
- src/quick-lint-js/diag/diagnostic-metadata-generated.h
- src/quick-lint-js/diag/diagnostic-types-2.h
- src/quick-lint-js/fe/parse-statement.cpp
- src/quick-lint-js/i18n/translation-table-generated.cpp
- src/quick-lint-js/i18n/translation-table-generated.h
- src/quick-lint-js/i18n/translation-table-test-generated.h
- test/test-parse-typescript-namespace.cpp
This closes #1139. I've moved `type_span` before switch statement so we can have better diagnostic instead of pointing on `import` keyword.
> feat(typescript): add new diag for "import type" with import alias

- fuzz/fuzz-configuration-json.cpp
- fuzz/fuzz-parse-lint.cpp
Building the fuzzers did not work for me.
It looks like the commit `8426914` broke the `fuzz/fuzz-configuration-json.cpp`
and the commit `fe5742f` broke the `fuzz/fuzz-parse-ling.cpp` 
I fixed the first issue, but I'm not quite sure how to fix the second one. I got the second one to compile, but now running `./build-fuzz/fuzz/quick-lint-js-fuzz-parse-lint` gives me an ASAN error. It looks to me like the Linter_Options have to be setup properly.
ASAN Error:
```
$ ./build-fuzz/fuzz/quick-lint-js-fuzz-parse-lint
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3978531955
INFO: Loaded 1 modules   (181238 inline 8-bit counters): 181238 [0x55f60eed08f0, 0x55f60eefcce6),
INFO: Loaded 1 PC tables (181238 PCs): 181238 [0x55f60eefcce8,0x55f60f1c0c48),
INFO: -max_len is not …
```
> Tries to fix the fuzzer build

- src/quick-lint-js/fe/parse-statement.cpp
- test/test-parse-statement.cpp
Added diagnostic when a 'for await' statement is in a non-async function, since this statement can only be used in contexts where 'await' can be used.
closes #1137
> feat: error on 'for await' in non-async function

- src/quick-lint-js/fe/lex.cpp
- test/test-parse-typescript-generic.cpp
fix(lex): parse `let f = (): RT<T>=>null;`
Test Plan:
`let f = (): RT<T>=>null;`
Fixes #1169
> fix(lex): parse `let f = (): RT<T>=>null;`

- plugin/vscode/quick-lint-js/vscode/qljs-document.cpp
- plugin/vscode/quick-lint-js/vscode/qljs-document.h
- plugin/vscode/quick-lint-js/vscode/qljs-workspace.h
- plugin/vscode/quick-lint-js/vscode/vscode-diag-reporter.h
refactor(vscode): inject translator and workspace
Summary: This commit refactors the global translator class into a variable
injected into the VSCode workspace, and gives the workspace as an argument to
QLJS_Lintable_Document.
This refactor clears the way for adding snarky and language settings for VSCode
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/quick-lint/quick-lint-js/pull/1189).
* #1190
* __->__ #1189
> refactor(vscode): inject translator and workspace

- README.md
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).
> Improve installation section in README
