- src/include/quick-lint-js/lex.h
- src/lex.cpp
- test/test-lex.cpp
This may resolve #5 if I understood the request.
> Report unexpected characters in hex literal

- test/test-file.cpp
> Implementation of tearDown method for tests to clean-up temp files

- tools/test-all-js-engines
Wrote this 2-minute script as part of https://github.com/strager/quick-lint-js/issues/7 , and figured since I wrote this anyways, might as well share it.
But looks like [Yahya doesn't like it](https://discordapp.com/channels/640652660839677962/640652660839677964/757730572129927309)
> Adds script to run js code through 3 popular js engines

- .github/workflows/build-and-test-web-demo.yml
Updated mymindstorm/setup-emsdk from v6 to v7 to fix @actions/core environment file syntax change warnings
> Update mymindstorm/setup-emsdk version

- src/lex.cpp
- src/quick-lint-js/error.h
- src/quick-lint-js/lex.h
- test/test-lex.cpp
Left some questions in comments as I was going through it.  Some of the question are obsolete
> Closes #7 : Octal literals

- README.md
README.md in the root describes QLJS's values, and the README.md in
plugin/vscode/ gives some examples as well as an animation.  This commit
combines the best from each
> 📝 Merge README.md and plugin/vscode/README.md

- dist/npm/package.json
I added a link to the repository.
> Add keywords to npm package

- website/hiring.html
- website/index.html
- website/install.html
- website/license.html
Added just for index.html. Do you want me to add for the other pages as well?
> Add <meta description> to index.html.

- website/demo/index.html
- website/install.html
Darken demo's text area (left-before and right-after):
Remove pixel under text area (top-before and bottom-after):
> Website: Small changes

- docs/errors/E077.md
- src/lint.cpp
- src/quick-lint-js/error.h
- test/test-lint.cpp
> Report warning for function declared in blocked scope and used before

- docs/errors/E086.md
- src/parse.cpp
- src/quick-lint-js/error.h
- test/test-parse-expression-statement.cpp
- test/test-parse-expression.cpp
> Report warning for redundant delete statement on variable

- docs/errors/E095.md
- src/lex.cpp
- src/quick-lint-js/error.h
- src/quick-lint-js/lex.h
- test/test-lex.cpp
> Report error on unicode BOM before #!

- completions/_quick-lint-js
- completions/quick-lint-js.bash
- completions/quick-lint-js.fish
- updated from 19cf27d56ab45f76643e49d745ea9bf0ac7a02c9
> patch to add `--stdin` in cli completions

- website/public/errors/index.ejs.html
Change the background-color to different color.
> Fix issue #271: "BOM" looking ugly on light mode

- src/parse.cpp
- src/quick-lint-js/parse.h
- test/test-lint-parse.cpp
- test/test-parse-expression.cpp
The following code should not report an error now:
const a = [42];
++a[0];
Fix: #307
>  Fix: False positive on const increment

- docs/errors/E202.md
- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-var.cpp
Now we report a missing equal error for the following code:
let x new Array();
Fixes: #304
> Improve diagnostic for variable assignment

- plugin/vim/README.md
- website/public/install/index.ejs.html
Update installation docs for moved repository: strager/quick-lint-js => quick-lint/quick-lint-js
> Update install docs for moved repo: strager/quick-lint-js => quick-lint/quick-lint-js

- .github/docker/Dockerfile
- .github/workflows/build-website.yml
- docs/config.adoc
- docs/man/quick-lint-js.config.5
- tools/check-links
Ensure all internal links on our website are working.
External links are not checked to avoid flakiness.
> CI: check for broken links on website

- website/public/index.ejs.html
In install option links, and feature comparison
table I fixed aria-labelled-by attribute to correct spelling
aria-labelledby. Fixed time element to have correct datetime attribute,
which translates dates into machine-readable format. Lastly, changed
obsolete tt element, in favor of code element. #335
> website:fix validation failures

- website/public/benchmarks/criterion-json-to-html.mjs
- website/public/cli/index.ejs.html
- website/public/config/index.ejs.html
- website/public/errors/index.ejs.html
- website/public/install/index.ejs.html
Fixed validation errors in install/error/cli/benchmark pages. #335
> Full website validation errors

- website/public/index.ejs.html
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md)
> updated the RSLint rules link

- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-class.cpp
> Improve error on 'async static' in class

- fuzz/fuzz-parse.cpp
This bug was introduced in commit b55b6b5.
> Fix fuzz-parse to call the correct function

- plugin/emacs/README.md
I was confused how to set up MELPA. Include more explicit documentation
on setup to help Emacs newbies.
> Emacs: improve install docs for LSP Mode and Flycheck

- plugin/emacs/flycheck-quicklintjs.el
- plugin/emacs/flymake-quicklintjs.el
> Emacs: use correct quick-lint-js.config file

- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-loop.cpp
for (const x = 10 of []) {}
for (let x = 10 in []) {}
Should report error_cannot_assign_to_loop_variable_in_for_of_or_in_loop.
> Report an error on initialization in for in/of loop

- tools/prune-old-builds.py
With this pull request I pretend to have a script which prune older builds that fit the following requirements:
* are older than 14 days
* are referenced by no branch
* are referenced by no pull request
> Create script to prune old builds (#367)

- completions/_quick-lint-js
- completions/quick-lint-js.bash
- completions/quick-lint-js.fish
- docs/cli.adoc
- docs/man/quick-lint-js.1
- plugin/vscode/quick-lint-js/vscode-error-reporter.h
- plugin/vscode/test/vscode-tests.js
- src/lsp-error-reporter.cpp
- src/main.cpp
- src/options.cpp
- src/quick-lint-js/options.h
- src/quick-lint-js/text-error-reporter.h
- src/text-error-reporter.cpp
- test/test-cli.py
- test/test-lsp-error-reporter.cpp
- test/test-lsp-server.cpp
- test/test-text-error-reporter.cpp
> CLI,  VSCode and LSP errors hyperlink to online docs

- website/public/robots.txt
issue #485
I added robots.txt.
I tested this locally using the  [Google's open source robots.txt library](https://github.com/google/robotstxt).
> Website: robots.txt

- src/quick-lint-js/error.h
- src/quick-lint-js/parse.h
- test/test-parse-statement.cpp
> Improve error for else (cond) {}

- .github/workflows/build-website.yml
- tools/check-links
- website/public/.htaccess
Added CI workflow step to test the website using Apache2.
> CI: test website with Apache #583

- src/lint.cpp
- src/quick-lint-js/error.h
- test/test-lint.cpp
Hello and happy new year 🎉 !
I'm making a PR for issue #373.
> Lint: Show more specific error when assigning to imported variable

- src/quick-lint-js/char8.h
- src/temporary-directory.cpp
and also delete an unnecessary one
> add missing include

- website/public/demo/index.ejs.html
- website/wasm/README.md
This pull request to resolve [#719](https://github.com/quick-lint/quick-lint-js/issues/719)
> Fix demo issue caused by codegrepper extension

- .github/workflows/build-website.yml
- website/public/.htaccess
this pull request resolves #477
> Website: improve security

- website/public/merch/index.ejs.html
Fixed the paypal button, this is my second pull request for this (I deleted the first one) because I couldn't sign the CLA due to some issues on my end with my github cli
> fixed pointer when hovering over paypal button

- docs/errors/E0286.md
- docs/errors/E0287.md
- po/de.po
- po/en_US@snarky.po
- po/fr_FR.po
- po/messages.pot
- po/sv_SE.po
- src/quick-lint-js/fe/diagnostic-types.h
- src/quick-lint-js/fe/parse-expression.cpp
- src/quick-lint-js/fe/parse.cpp
- src/quick-lint-js/fe/parse.h
- src/quick-lint-js/i18n/translation-table-generated.cpp
- src/quick-lint-js/i18n/translation-table-generated.h
- src/quick-lint-js/port/char8.cpp
- src/quick-lint-js/port/char8.h
- test/quick-lint-js/test-translation-table-generated.h
- test/test-parse-warning.cpp
> Fix #741: Warn on 'x.toLowerCase() == "BANANA"'

- docs/TRANSLATING.md
- tools/format
- tools/update-translator-sources
> Check go version and xgettext

- website/wasm/quick-lint-js.js
> fix(website): added missing properties.

- docs/errors/E0349.md
- po/de.po
- po/en_US@snarky.po
- po/fr_FR.po
- po/messages.pot
- po/pt_BR.po
- po/sv_SE.po
- src/quick-lint-js/fe/diagnostic-types.h
- src/quick-lint-js/fe/parse-expression.cpp
- src/quick-lint-js/fe/parse-statement.cpp
- src/quick-lint-js/i18n/translation-table-generated.cpp
- src/quick-lint-js/i18n/translation-table-generated.h
- test/quick-lint-js/test-translation-table-generated.h
- test/test-parse-function.cpp
- test/test-translation-table-generated.cpp
- added diagnostic type
- added reporting in statement and expression parsing
- updated the translation
- modified existing test for the error
- added test for the error
Closes #852
> Added error E0349 for parenthesized parameter

- src/quick-lint-js/fe/parse.cpp
- test/test-parse-warning.cpp
- null was working already, added check for undefined
- added tests for null and undefined
closes #836
> feature : added null and undefined in E0109

- docs/errors/E0062.md
- src/quick-lint-js/fe/parse-statement.cpp
This commit improves the error recovery for IIFE, which was required for the changes we made in #940 for #939.
> Enhance error recovery for IIFE

- src/quick-lint-js/fe/parse-expression.cpp
- test/test-parse-function.cpp
> feat(fe): error on trailing comma in return

- website/public/index.ejs.html
- website/public/main.css
-Removed CTAs on Mobile
-Shrank The first Table on Mobile
-Replaced The second table with the "Editors Support" section
> Website: improve mobile experience on home page issue #897

- .gitignore
hi @strager. I am adding two path to be ignored in this PR. There are hundreds of items that pollute my git changes viewer everytime I want to commit a change. This is relevant to anyone using a windows dev env setup to contribute.
> updating .gitignore to accomodate windows dev env setup

- src/quick-lint-js/io/file-handle-posix.cpp
> Fix FreeBSD Build
